"""
SchemaTracker — Ada watches her own schema grow.

Every fact passes through the enricher and yields a StructuredFact with a
predicate and a topic. As novel facts arrive, novel predicates and topics
appear. SchemaTracker:

  1. Watches every absorb() and notes the first time it sees a predicate
     or a topic.
  2. Logs the discovery to a markdown file (default `docs/schema_history.md`)
     so the schema changelog lives in git and is human-reviewable.
  3. Absorbs a meta-glyph back into the substrate describing the new schema
     element, with a stable key like `schema.predicate.favorite_color`.
     The substrate now knows about its own schema and can recall it.

Both representations are the source of truth in parallel. You can grep
the markdown to audit what Ada has learned, or query the substrate
("what predicates exist about people?") to ask Ada the same thing.

Usage:
    space = ThoughtGlyphSpace(enricher=enricher)
    tracker = SchemaTracker(space)
    for fact in corpus:
        stored = space.absorb(fact)
        if stored:
            tracker.observe(stored)
    print(tracker.summary())
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


# ── Tracker ──────────────────────────────────────────────────────────

DEFAULT_HISTORY_PATH = "docs/schema_history.md"
DEFAULT_HEADER = """# Schema history

Auto-generated by `ada.skill.SchemaTracker`. Each entry records the first
time the substrate encountered a new predicate or topic, with the
exemplar fact that introduced it. Newest entries appended at the bottom.

Format per entry:
- timestamp
- what's new (predicate, topic, or both)
- the exemplar fact that introduced it
- the meta-glyph thought_id that now lives in the substrate
"""


@dataclass
class SchemaState:
    """Running tally of what the substrate has learned about its own structure."""
    predicates: dict[str, int] = field(default_factory=dict)   # predicate → count
    topics: dict[str, int] = field(default_factory=dict)        # topic → count
    introductions: list[dict] = field(default_factory=list)     # ordered log

    def is_known_predicate(self, p: str) -> bool:
        return p in self.predicates

    def is_known_topic(self, t: str) -> bool:
        return t in self.topics


class SchemaTracker:
    """Watch the substrate's evolving schema; persist as markdown + meta-glyphs."""

    def __init__(
        self,
        space: "object",     # ThoughtGlyphSpace; avoid circular import
        history_path: str = DEFAULT_HISTORY_PATH,
        write_markdown: bool = True,
        write_meta_glyph: bool = True,
    ) -> None:
        self.space = space
        self.history_path = Path(history_path)
        self.write_markdown = write_markdown
        self.write_meta_glyph = write_meta_glyph
        self.state = SchemaState()
        if self.write_markdown:
            self.history_path.parent.mkdir(parents=True, exist_ok=True)
            if not self.history_path.exists():
                self.history_path.write_text(DEFAULT_HEADER)

    # ── core observation ──────────────────────────────────────────────

    def observe(self, stored: "object") -> dict:
        """Watch this absorb's result. Return info about what's new.

        `stored` is a StoredThought. We pull the StructuredFact from
        glyph.metadata['_structured'] and decide if it's the first time
        we're seeing its predicate or topic.
        """
        sf = stored.glyph.metadata.get("_structured")
        if sf is None or not sf.is_structured():
            return {"new_predicate": False, "new_topic": False}

        new_p = bool(sf.predicate) and not self.state.is_known_predicate(sf.predicate)
        new_t = bool(sf.topic) and sf.topic != "general" \
                                and not self.state.is_known_topic(sf.topic)

        if sf.predicate:
            self.state.predicates[sf.predicate] = self.state.predicates.get(sf.predicate, 0) + 1
        if sf.topic and sf.topic != "general":
            self.state.topics[sf.topic] = self.state.topics.get(sf.topic, 0) + 1

        if new_p or new_t:
            meta_thought_id = self._persist_introduction(stored, sf, new_p, new_t)
            self.state.introductions.append({
                "ts": datetime.now(timezone.utc).isoformat(),
                "new_predicate": sf.predicate if new_p else None,
                "new_topic": sf.topic if new_t else None,
                "exemplar": sf.text,
                "meta_thought_id": meta_thought_id,
            })

        return {"new_predicate": new_p, "new_topic": new_t}

    # ── persistence (markdown + meta-glyph) ───────────────────────────

    def _persist_introduction(self, stored, sf, new_p: bool, new_t: bool) -> Optional[str]:
        # Build a single sentence describing the discovery (used by both paths).
        parts = []
        if new_p:
            parts.append(f"predicate '{sf.predicate}'")
        if new_t:
            parts.append(f"topic '{sf.topic}'")
        what = " and ".join(parts)
        descr = (
            f"Schema introduction: new {what}. "
            f"First exemplar: {sf.text!r} "
            f"(subject='{sf.subject}', object='{sf.object}')."
        )

        meta_id: Optional[str] = None

        # 1. Append to the markdown changelog.
        if self.write_markdown:
            with self.history_path.open("a", encoding="utf-8") as fh:
                fh.write(f"\n## {datetime.now(timezone.utc).isoformat()}\n\n")
                if new_p:
                    fh.write(f"- **new predicate**: `{sf.predicate}`\n")
                if new_t:
                    fh.write(f"- **new topic**: `{sf.topic}`\n")
                fh.write(f"- **exemplar**: {sf.text}\n")
                fh.write(f"- **subject** / **object**: `{sf.subject}` / `{sf.object}`\n")

        # 2. Absorb a meta-glyph into the substrate so it can recall its
        #    own schema. Stable key so the same introduction over time
        #    becomes a versioned chain (sim history of the schema concept).
        if self.write_meta_glyph:
            if new_p:
                key = f"schema.predicate.{sf.predicate}"
            else:
                key = f"schema.topic.{sf.topic.replace('.', '_')}"
            meta_stored = self.space.absorb(descr, speaker="schema", key=key)
            if meta_stored is not None:
                meta_id = meta_stored.thought_id
                # Backlink the meta-glyph from the changelog line.
                if self.write_markdown:
                    with self.history_path.open("a", encoding="utf-8") as fh:
                        fh.write(f"- **meta-glyph**: `{meta_id}`\n")

        return meta_id

    # ── summary ───────────────────────────────────────────────────────

    def summary(self) -> dict:
        return {
            "predicates_known": len(self.state.predicates),
            "topics_known": len(self.state.topics),
            "introductions": len(self.state.introductions),
            "top_predicates": sorted(self.state.predicates.items(), key=lambda kv: -kv[1])[:5],
            "top_topics": sorted(self.state.topics.items(), key=lambda kv: -kv[1])[:5],
        }
